# Generated by Django 5.1.5 on 2025-01-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_comment_id_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('user', 'project')},
        ),
    ]
